---
abstract: 'Access run information from the Zombies, Run! game'
author:
  - 'Paul Fenwick <pjf@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-ZombiesRun
requires:
  Data::Dumper: 0
  JSON::Any: 0
  Moo: 0
  WWW::Mechanize: 0
  autodie: 0
  constant: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/pjf/WebService-ZombiesRun
version: 0.01
